### ISSUE TITLE
highlight TOC in sidebar according to scrolling

### ISSUE THREAD

**Issue by canalun** [k-yokoishi/keynotion#1]
Thank you for developing this great app :)

What do you think about highlighting TOC in the sidebar according to scrolling?
It would look nice if we adopted the same style of highlight as the original Notion.

If this idea seems to be good, I'd like to try on it😊

**Comment by canalun** [comment]
FYI) prototype is like this

https://github.com/k-yokoishi/keynotion/assets/61643630/7807ecc2-edec-480e-ba17-5e9c640af1b3

**Comment by k-yokoishi** [comment]
@canalun 
Thank you for the great suggestion! I completely agree with you.
While I hope you’ll bring that idea to life, I’d be happy to help you if needed. Let's work on designing it together!

**Comment by canalun** [comment]
Thanks!
I modified the prototype and created PR #2.
please take a look :)

**Comment by canalun** [comment]
merged!
